// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "actqj71e71tcp3.h"

/////////////////////////////////////////////////////////////////////////////
// CActQJ71E71TCP3

IMPLEMENT_DYNCREATE(CActQJ71E71TCP3, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CActQJ71E71TCP3 properties

/////////////////////////////////////////////////////////////////////////////
// CActQJ71E71TCP3 operations

long CActQJ71E71TCP3::Open()
{
	long result;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CActQJ71E71TCP3::Close()
{
	long result;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CActQJ71E71TCP3::ReadDeviceBlock(LPCTSTR szDevice, long dwSize, long* lpdwData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_PI4;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDevice, dwSize, lpdwData);
	return result;
}

long CActQJ71E71TCP3::WriteDeviceBlock(LPCTSTR szDevice, long dwSize, long* lpdwData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_PI4;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDevice, dwSize, lpdwData);
	return result;
}

long CActQJ71E71TCP3::ReadDeviceRandom(LPCTSTR szDeviceList, long dwSize, long* lpdwData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_PI4;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDeviceList, dwSize, lpdwData);
	return result;
}

long CActQJ71E71TCP3::WriteDeviceRandom(LPCTSTR szDeviceList, long dwSize, long* lpdwData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_PI4;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDeviceList, dwSize, lpdwData);
	return result;
}

long CActQJ71E71TCP3::ReadBuffer(long lStartIO, long lAddress, long lReadSize, short* lpwData)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_PI2;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		lStartIO, lAddress, lReadSize, lpwData);
	return result;
}

long CActQJ71E71TCP3::WriteBuffer(long lStartIO, long lAddress, long lWriteSize, short* lpwData)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_PI2;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		lStartIO, lAddress, lWriteSize, lpwData);
	return result;
}

long CActQJ71E71TCP3::GetClockData(short* lpwYear, short* lpwMonth, short* lpwDay, short* lpwDayOfWeek, short* lpwHour, short* lpwMinute, short* lpwSecond)
{
	long result;
	static BYTE parms[] =
		VTS_PI2 VTS_PI2 VTS_PI2 VTS_PI2 VTS_PI2 VTS_PI2 VTS_PI2;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		lpwYear, lpwMonth, lpwDay, lpwDayOfWeek, lpwHour, lpwMinute, lpwSecond);
	return result;
}

long CActQJ71E71TCP3::SetClockData(short wYear, short wMonth, short wDay, short wDayOfWeek, short wHour, short wMinute, short wSecond)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		wYear, wMonth, wDay, wDayOfWeek, wHour, wMinute, wSecond);
	return result;
}

long CActQJ71E71TCP3::SetDevice(LPCTSTR szDevice, long dwData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDevice, dwData);
	return result;
}

long CActQJ71E71TCP3::SetCpuStatus(long lOperation)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		lOperation);
	return result;
}

long CActQJ71E71TCP3::GetCpuType(BSTR* szCpuName, long* lplCpuType)
{
	long result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI4;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szCpuName, lplCpuType);
	return result;
}

long CActQJ71E71TCP3::GetActNetworkNumber()
{
	long result;
	InvokeHelper(0xe, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CActQJ71E71TCP3::SetActNetworkNumber(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xe, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CActQJ71E71TCP3::GetActStationNumber()
{
	long result;
	InvokeHelper(0xf, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CActQJ71E71TCP3::SetActStationNumber(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xf, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CActQJ71E71TCP3::GetActUnitNumber()
{
	long result;
	InvokeHelper(0x10, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CActQJ71E71TCP3::SetActUnitNumber(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x10, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CActQJ71E71TCP3::GetActConnectUnitNumber()
{
	long result;
	InvokeHelper(0x11, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CActQJ71E71TCP3::SetActConnectUnitNumber(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x11, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CActQJ71E71TCP3::GetActIONumber()
{
	long result;
	InvokeHelper(0x12, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CActQJ71E71TCP3::SetActIONumber(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x12, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CActQJ71E71TCP3::GetActCpuType()
{
	long result;
	InvokeHelper(0x13, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CActQJ71E71TCP3::SetActCpuType(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x13, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

CString CActQJ71E71TCP3::GetActHostAddress()
{
	CString result;
	InvokeHelper(0x15, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CActQJ71E71TCP3::SetActHostAddress(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x15, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

long CActQJ71E71TCP3::GetActTimeOut()
{
	long result;
	InvokeHelper(0x16, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CActQJ71E71TCP3::SetActTimeOut(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x16, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CActQJ71E71TCP3::GetActSourceNetworkNumber()
{
	long result;
	InvokeHelper(0x17, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CActQJ71E71TCP3::SetActSourceNetworkNumber(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x17, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CActQJ71E71TCP3::GetActSourceStationNumber()
{
	long result;
	InvokeHelper(0x18, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CActQJ71E71TCP3::SetActSourceStationNumber(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x18, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CActQJ71E71TCP3::GetActDestinationIONumber()
{
	long result;
	InvokeHelper(0x19, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CActQJ71E71TCP3::SetActDestinationIONumber(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x19, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CActQJ71E71TCP3::GetActMultiDropChannelNumber()
{
	long result;
	InvokeHelper(0x1a, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CActQJ71E71TCP3::SetActMultiDropChannelNumber(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CActQJ71E71TCP3::GetActThroughNetworkType()
{
	long result;
	InvokeHelper(0x1b, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CActQJ71E71TCP3::SetActThroughNetworkType(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CActQJ71E71TCP3::GetActDidPropertyBit()
{
	long result;
	InvokeHelper(0x1c, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CActQJ71E71TCP3::SetActDidPropertyBit(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CActQJ71E71TCP3::GetActDsidPropertyBit()
{
	long result;
	InvokeHelper(0x1d, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CActQJ71E71TCP3::SetActDsidPropertyBit(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CActQJ71E71TCP3::GetDevice(LPCTSTR szDevice, long* lpdwData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_PI4;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDevice, lpdwData);
	return result;
}

long CActQJ71E71TCP3::CheckDeviceString(LPCTSTR szDevice, long lCheckType, long lSize, long* lplDeviceType, BSTR* lpszDeviceName, long* lplDeviceNumber, long* lplDeviceRadix)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_PI4 VTS_PBSTR VTS_PI4 VTS_PI4;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDevice, lCheckType, lSize, lplDeviceType, lpszDeviceName, lplDeviceNumber, lplDeviceRadix);
	return result;
}

long CActQJ71E71TCP3::EntryDeviceStatus(LPCTSTR szDeviceList, long lSize, long lMonitorCycle, long* lplData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_PI4;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDeviceList, lSize, lMonitorCycle, lplData);
	return result;
}

long CActQJ71E71TCP3::FreeDeviceStatus()
{
	long result;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CActQJ71E71TCP3::GetActPassword()
{
	CString result;
	InvokeHelper(0x23, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CActQJ71E71TCP3::SetActPassword(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x23, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

long CActQJ71E71TCP3::ReadDeviceBlock2(LPCTSTR szDevice, long lSize, short* lpsData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_PI2;
	InvokeHelper(0x24, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDevice, lSize, lpsData);
	return result;
}

long CActQJ71E71TCP3::WriteDeviceBlock2(LPCTSTR szDevice, long lSize, short* lpsData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_PI2;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDevice, lSize, lpsData);
	return result;
}

long CActQJ71E71TCP3::ReadDeviceRandom2(LPCTSTR szDevice, long lSize, short* lpsData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_PI2;
	InvokeHelper(0x26, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDevice, lSize, lpsData);
	return result;
}

long CActQJ71E71TCP3::WriteDeviceRandom2(LPCTSTR szDeviceList, long lSize, short* lpsData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_PI2;
	InvokeHelper(0x27, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDeviceList, lSize, lpsData);
	return result;
}

long CActQJ71E71TCP3::GetDevice2(LPCTSTR szDevice, short* lpsData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_PI2;
	InvokeHelper(0x28, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDevice, lpsData);
	return result;
}

long CActQJ71E71TCP3::SetDevice2(LPCTSTR szDevice, short sData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x29, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDevice, sData);
	return result;
}
