#if !defined(AFX_ACTQJ71E71TCP3_H__099A7F8D_A90E_4BA0_9E1F_422E612E4E77__INCLUDED_)
#define AFX_ACTQJ71E71TCP3_H__099A7F8D_A90E_4BA0_9E1F_422E612E4E77__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CActQJ71E71TCP3 wrapper class

class CActQJ71E71TCP3 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CActQJ71E71TCP3)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xafea5512, 0xae9c, 0x11d3, { 0x83, 0xae, 0x0, 0xa0, 0x24, 0xbd, 0xbf, 0x2b } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long Open();
	long Close();
	long ReadDeviceBlock(LPCTSTR szDevice, long dwSize, long* lpdwData);
	long WriteDeviceBlock(LPCTSTR szDevice, long dwSize, long* lpdwData);
	long ReadDeviceRandom(LPCTSTR szDeviceList, long dwSize, long* lpdwData);
	long WriteDeviceRandom(LPCTSTR szDeviceList, long dwSize, long* lpdwData);
	long ReadBuffer(long lStartIO, long lAddress, long lReadSize, short* lpwData);
	long WriteBuffer(long lStartIO, long lAddress, long lWriteSize, short* lpwData);
	long GetClockData(short* lpwYear, short* lpwMonth, short* lpwDay, short* lpwDayOfWeek, short* lpwHour, short* lpwMinute, short* lpwSecond);
	long SetClockData(short wYear, short wMonth, short wDay, short wDayOfWeek, short wHour, short wMinute, short wSecond);
	long SetDevice(LPCTSTR szDevice, long dwData);
	long SetCpuStatus(long lOperation);
	long GetCpuType(BSTR* szCpuName, long* lplCpuType);
	long GetActNetworkNumber();
	void SetActNetworkNumber(long nNewValue);
	long GetActStationNumber();
	void SetActStationNumber(long nNewValue);
	long GetActUnitNumber();
	void SetActUnitNumber(long nNewValue);
	long GetActConnectUnitNumber();
	void SetActConnectUnitNumber(long nNewValue);
	long GetActIONumber();
	void SetActIONumber(long nNewValue);
	long GetActCpuType();
	void SetActCpuType(long nNewValue);
	CString GetActHostAddress();
	void SetActHostAddress(LPCTSTR lpszNewValue);
	long GetActTimeOut();
	void SetActTimeOut(long nNewValue);
	long GetActSourceNetworkNumber();
	void SetActSourceNetworkNumber(long nNewValue);
	long GetActSourceStationNumber();
	void SetActSourceStationNumber(long nNewValue);
	long GetActDestinationIONumber();
	void SetActDestinationIONumber(long nNewValue);
	long GetActMultiDropChannelNumber();
	void SetActMultiDropChannelNumber(long nNewValue);
	long GetActThroughNetworkType();
	void SetActThroughNetworkType(long nNewValue);
	long GetActDidPropertyBit();
	void SetActDidPropertyBit(long nNewValue);
	long GetActDsidPropertyBit();
	void SetActDsidPropertyBit(long nNewValue);
	long GetDevice(LPCTSTR szDevice, long* lpdwData);
	long CheckDeviceString(LPCTSTR szDevice, long lCheckType, long lSize, long* lplDeviceType, BSTR* lpszDeviceName, long* lplDeviceNumber, long* lplDeviceRadix);
	long EntryDeviceStatus(LPCTSTR szDeviceList, long lSize, long lMonitorCycle, long* lplData);
	long FreeDeviceStatus();
	CString GetActPassword();
	void SetActPassword(LPCTSTR lpszNewValue);
	long ReadDeviceBlock2(LPCTSTR szDevice, long lSize, short* lpsData);
	long WriteDeviceBlock2(LPCTSTR szDevice, long lSize, short* lpsData);
	long ReadDeviceRandom2(LPCTSTR szDevice, long lSize, short* lpsData);
	long WriteDeviceRandom2(LPCTSTR szDeviceList, long lSize, short* lpsData);
	long GetDevice2(LPCTSTR szDevice, short* lpsData);
	long SetDevice2(LPCTSTR szDevice, short sData);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ACTQJ71E71TCP3_H__099A7F8D_A90E_4BA0_9E1F_422E612E4E77__INCLUDED_)
