#ifndef __FASDEFINE_H__
#define __FASDEFINE_H__

////////////////////////////////////////////////////////////////////////////

// System(Global) Parameter List
#define _FAS_GLOBAL_INTERACCDEC			10
#define _FAS_GLOBAL_GRAPH_MONITORING	29
#define _FAS_GLOBAL_CORNERONOFFSET		33

typedef enum _GLOBAL_PARA
{
	_NO_OF_CONTROL_AXIS = 0,	// 0
	_ACC_DEC_METHOD,		
	_TIME_OR_ACCEL,
	_INTER_START_FEEDRATE,
	_SOFT_LIMIT_STOP_METHOD,
	_ORG_RETURN_ERR_TIME,
	_SERVO_ERR_COUNTER_CLEAR_TIME,
	_SENSOR_AND_SERVO_INPUT_FILTER,
	_GENERAL_IO_INPUT_FILTER,
	_INTER_MAX_FEEDRATE,
	_INTER_ACC_TIME,			// 10
	_INTER_FEED_OVERRIDE,
	_HAND_WHEEL_EXIST_FLAG,
	_HAND_WHEEL_DIR,
	_HAND_WHEEL_MULTI,
	_HAND_WHEEL_RATIO,
	_SERVO_ERR_COUNTER_CLEAR_ENABLE,
	_CORNER_HEIGHT_COMP_METHOD,
	_CONTER_HEIGHT_COMP_DISTANCE,
	_CORNER_THICKNESS1_OF_SPEED1,
	_CORNER_THICHNESS2_OF_SPEED2,	// 20
	_CORNER_THICKNESS1_OF_HEIGHT1,
	_CORNER_THICKNESS2_OF_HEIGH2,
	_CORNER_SPEED1,
	_CORNER_SPEED2,
	_CORNER_HEIGHT1,
	_CORNER_HEIGHT2,
	_CORNER_HEIGHT_AT_CIRCLE_MOVE,
	_CORNER_HEIGHT_COMP_ENABLE,
	_GRAPH_MONITORING_ENABLE,
	_GRAPH_MONITORING_AXIS,			// 30
	_GANTRY_DROP,
	_DROP_CONTROL_SYNC_IO_ENABLE,
	_PRESSURE_CONTROL_START_DISTANCE,
	_GLOBAL_AAA,
	_OMRON_CHANNEL_OFFSET,
	_CORNER_GAP_COMP_START_POINT,
	_CORNER_GAP_NO_OF_COMP,
	_CORNER_GAP_INC_DISTANCE,
} GLOBAL_PARA;

// Local Parameter List
typedef enum _LOCAL_PARA
{
	_AXIS_CONTROL_MOTOR = 0,	// 0
	_PULSE_OUT_METHOD,
	_MOTION_DIR,
	_AXIS_MAX_SPEED,
	_AXIS_START_SPEED,
	_AXIS_ACC_TIME,
	_AXIS_DEC_TIME,
	_SPEED_OVERRIDE,
	_JOG_SPEED,
	_JOG_ACC_TIME,
	_ORG_HIGH_SPEED,		// 10
	_ORG_LOW_SPEED,
	_ORG_ACC_TIME,
	_ORG_METHOD,
	_ORG_DIR,
	_ORG_OFFSET,
	_ORG_POSITOIN_SET,
	_ORG_INDEX_PULSE_LOGIC,
	_ORG_SENSOR_LOGIC,
	_LIMIT_SENSOR_LOGIC,
	_SERVO_ON_LOGIC,		// 20
	_SERVO_RESET_LOGIC,
	_SERVO_ERR_CLEAR_LOGIC,
	_SERVO_ALARM_LOGIC,
	_SERVO_INPOS_LOGIC,
	_SERVO_INPOS_CHECK_TIME,
	_SERVO_INPOS_CHECK_FLAG,
	_SERVO_INPOS_VALUE,
	_POS_TRACKING_LIMIT,
	_SW_LIMIT_PLUS_VALUE,
	_SW_LIMIT_MINUS_VALUE,	// 30
	_ENCODER_CONTROL_METHOD,
	_ENCODER_GEAR_BUNJA,
	_ENCODER_GEAR_BUNMO,
	_ENCODER_DIR,
	_ENCODER_MULTI_RATIO,
	_DUAL_FEEDBACK_CHECK_ZONE,
	_DUAL_FEEDBACK_CHECK_TIME,
	_DUAL_FEEDBACK_CHECK_NO,
	_SMOOTHING_START_PULSE,
	_VIBRATION_COMP_TIME,	// 40
	_BACKLASH_COMP_VALUE,
	_ERROR_SIMUL_STOP_FLAG,
	_AD_INPUT_RNAGE,
	_LASER_RANGE,
	_GAP_COMP_MIN_RANGE,
	_GAP_COMP_MAX_RANGE,
	_GAP_COMP_DIFF_RANGE,
	_GAP_COMP_SPEED,
	_GAP_COMP_DELAY,
	_GAP_COMP_CANCEL_COUNT,		// 50
	_GAP_TARGET_POS,
	_ENCODER_FILTER,
	_AXIS_LASER_INPUT_BIT,
	_CORNER_COMP_ENABLE,
	_CORNER_COMP_DISTANCE,
	_ORG_SEARCH_SPEED,
	_HARD_LIMIT_STOP_METHOD,
	_CORNER_COMP_SPEED,
	_AD_FILTER_LENGTH,
	_LASER_FILTER_LENGTH,		// 60
	_GAP_COMP_OUTPUT_LIMIT,
	_GAP_MOTOR_ACTIVE_RANGE,
	_LASER_SENSOR_TYPE,
	_PRESSURE_CONTROL_IO_BIT,
	_GAP_ACC_DEC_TIME,
	_CORNER_GAP_CONTROL_ENABLE,
	_CORNER_GAP_COMP_VALUE,
	_CORNER_GAP_SCAN_DELAY_INC,
	_GAP_START_SPEED
} LOCAL_PARA;

// Axis Status List
#define _AXIS_ERR_ALL				0x00000001
#define _AXIS_ERR_SERVO_ALARM		0x00000002
#define _AXIS_INPOS_TIMEOUT			0x00000004
#define _AXIS_HW_FW_LIMIT			0x00000008
#define _AXIS_HW_BW_LIMIT			0x00000010
#define _AXIS_SW_FW_LIMIT			0x00000020
#define _AXIS_SW_BW_LIMIT			0x00000040
#define _AXIS_ORIGIN_TIMEOUT		0x00000080
#define _AXIS_POS_TRACKING			0x00000100
#define _AXIS_POS_COUNT_OVER		0x00000200
#define _AXIS_EMG_STOP				0x00000400
#define _AXIS_ERR_SET_DATA			0x00000800
#define _AXIS_Q_FULL				0x00001000
#define _AXIS_IO_Q_FULL				0x00002000
#define _AXIS_END_FEEDBACK			0x00004000
#define _AXIS_ERR_HANDWHEEL			0x00008000
#define _AXIS_START					0x00010000
#define _AXIS_SLOW_STOP				0x00020000
#define _AXIS_ZERO_RETURNING		0x00040000
#define _AXIS_INPOSITION			0x00080000
#define _AXIS_SERVO_ON				0x00100000
#define _AXIS_ALARM_RESET			0x00200000
#define _AXIS_COUNTER_CLEAR			0x00400000
#define _AXIS_HOME_SENSOR			0x00800000
#define _AXIS_Z_PULSE				0x01000000
#define _AXIS_ZERO_RET_OK			0x02000000
#define _AXIS_MOTION_DIR			0x04000000
#define _AXIS_MOTIONING				0x08000000
#define _AXIS_MOTION_PAUSE			0x10000000
#define _AXIS_MOTION_ACCEL			0x20000000
#define _AXIS_MOTOIN_DECEL			0x40000000
#define _AXIS_MOTION_CONSTANT		0x80000000

#endif