// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "kovision.h"

/////////////////////////////////////////////////////////////////////////////
// CKOVISION

IMPLEMENT_DYNCREATE(CKOVISION, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CKOVISION properties

/////////////////////////////////////////////////////////////////////////////
// CKOVISION operations

long CKOVISION::LineFittingHor(long dataN, double* x, double* y, long removeN, double ErrorLimit, double* t, double* a, double* b)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_PR8 VTS_PR8 VTS_I4 VTS_R8 VTS_PR8 VTS_PR8 VTS_PR8;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		dataN, x, y, removeN, ErrorLimit, t, a, b);
	return result;
}

long CKOVISION::LineFittingVer(long dataN, double* x, double* y, long removeN, double ErrorLimit, double* t, double* a, double* b)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_PR8 VTS_PR8 VTS_I4 VTS_R8 VTS_PR8 VTS_PR8 VTS_PR8;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		dataN, x, y, removeN, ErrorLimit, t, a, b);
	return result;
}

long CKOVISION::LineCrossPoint(double t1, double a1, double b1, double t2, double a2, double b2, double* cx, double* cy)
{
	long result;
	static BYTE parms[] =
		VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_PR8 VTS_PR8;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		t1, a1, b1, t2, a2, b2, cx, cy);
	return result;
}

long CKOVISION::SetLineData(long nSlope, double dRemoveRate, double dLimitPixel)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_R8 VTS_R8;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nSlope, dRemoveRate, dLimitPixel);
	return result;
}

BOOL CKOVISION::Open()
{
	BOOL result;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

long CKOVISION::FindCornerPos(long fm, long left, long top, long right, long bottom, long nPitch, long nCorner_Pos, long nObject_Color, long nSkip, long Result_Show, long nAllowedRange, double* x, double* y, double* x_good_ratio, double* y_good_ratio)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_PR8 VTS_PR8 VTS_PR8 VTS_PR8;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		fm, left, top, right, bottom, nPitch, nCorner_Pos, nObject_Color, nSkip, Result_Show, nAllowedRange, x, y, x_good_ratio, y_good_ratio);
	return result;
}

long CKOVISION::FindVer2Line(long fm, long left, long top, long right, long bottom, long nPitch, double dObject_Width, long nObject_Color, long nSkip, long Result_Show, long nRotate_Range, double* t, double* a, double* b)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_R8 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_PR8 VTS_PR8 VTS_PR8;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		fm, left, top, right, bottom, nPitch, dObject_Width, nObject_Color, nSkip, Result_Show, nRotate_Range, t, a, b);
	return result;
}

long CKOVISION::FindHor2Line(long fm, long left, long top, long right, long bottom, long nPitch, double dObject_Width, long nObject_Color, long nSkip, long Result_Show, long nRotate_Range, double* t, double* a, double* b)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_R8 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_PR8 VTS_PR8 VTS_PR8;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		fm, left, top, right, bottom, nPitch, dObject_Width, nObject_Color, nSkip, Result_Show, nRotate_Range, t, a, b);
	return result;
}

long CKOVISION::FindImageAngle(long fm, long left, long top, long right, long bottom, long nPitch, double* pAngleTotal, double* pAngleMax)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_PR8 VTS_PR8;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		fm, left, top, right, bottom, nPitch, pAngleTotal, pAngleMax);
	return result;
}

double CKOVISION::FindWidth(long fm, long left, long top, long right, long bottom, long pitch, long nColor, long nDir, long nMinDiff, long nPixelOffset, long nFindMax, double* rx, double* ry)
{
	double result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_PR8 VTS_PR8;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		fm, left, top, right, bottom, pitch, nColor, nDir, nMinDiff, nPixelOffset, nFindMax, rx, ry);
	return result;
}

long CKOVISION::FindWidth1(long fm, long left, long top, long right, long bottom, long pitch, long nColor, long nDir, long nMinDiff, long nPixelOffset, long nFindMax, double* rx, double* ry, double* widthNormal, double* widthShort)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_PR8 VTS_PR8 VTS_PR8 VTS_PR8;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		fm, left, top, right, bottom, pitch, nColor, nDir, nMinDiff, nPixelOffset, nFindMax, rx, ry, widthNormal, widthShort);
	return result;
}

long CKOVISION::ImageRotate(long fmS, long fmD, long left, long top, long right, long bottom, long pitch, double dCx, double dCy, double dAngle)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_R8 VTS_R8 VTS_R8;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		fmS, fmD, left, top, right, bottom, pitch, dCx, dCy, dAngle);
	return result;
}

long CKOVISION::SetCodeData(long nCodeType, long nConfirm, long nSkipY, long nShowLine, long nShowAstrisk, long nDataSizeFixed, long nDataSize)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCodeType, nConfirm, nSkipY, nShowLine, nShowAstrisk, nDataSizeFixed, nDataSize);
	return result;
}

long CKOVISION::GetCodeData(long* nCodeType, long* nConfirm, long* nSkipY, long* nShowLine, long* nShowAstrisk, long* nDataSizeFixed, long* nDataSize)
{
	long result;
	static BYTE parms[] =
		VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI4;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCodeType, nConfirm, nSkipY, nShowLine, nShowAstrisk, nDataSizeFixed, nDataSize);
	return result;
}

CString CKOVISION::ReadBarcode(long fm, long left, long top, long right, long bottom, long pitch)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		fm, left, top, right, bottom, pitch);
	return result;
}

long CKOVISION::SaveCodeData(LPCTSTR pFileName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		pFileName);
	return result;
}

long CKOVISION::LoadCodeData(LPCTSTR pFileName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		pFileName);
	return result;
}

CString CKOVISION::ReadBarcode1(long fm, long left, long top, long right, long bottom, long pitch, long nProjNum, long nTry, long nStartDepth, long nEndDepth)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		fm, left, top, right, bottom, pitch, nProjNum, nTry, nStartDepth, nEndDepth);
	return result;
}

CString CKOVISION::ReadBarcodeVer(long fm, long left, long top, long right, long bottom, long pitch)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		fm, left, top, right, bottom, pitch);
	return result;
}

CString CKOVISION::ReadBarcode1Ver(long fm, long left, long top, long right, long bottom, long pitch, long ProjNum, long nTry, long nStartDepth, long nEndDepth)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		fm, left, top, right, bottom, pitch, ProjNum, nTry, nStartDepth, nEndDepth);
	return result;
}

long CKOVISION::SetBase(long nCam, double dCx, double dCy, double dAngle)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_R8 VTS_R8 VTS_R8;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCam, dCx, dCy, dAngle);
	return result;
}

long CKOVISION::SetBase2Point(long nCam, double dCx1, double dCy1, double dCx2, double dCy2)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_R8 VTS_R8 VTS_R8 VTS_R8;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCam, dCx1, dCy1, dCx2, dCy2);
	return result;
}

long CKOVISION::GetOffset2Point(long nCam, double dCx1, double dCy1, double dCx2, double dCy2, double* dOffsetX, double* dOffsetY, double* dAngle)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_PR8 VTS_PR8 VTS_PR8;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCam, dCx1, dCy1, dCx2, dCy2, dOffsetX, dOffsetY, dAngle);
	return result;
}

long CKOVISION::SetBase2Point2Pos(long nCam, double dRobotX1, double dRobotY1, double dRobotX2, double dRobotY2, double dPixelX1, double dPixelY1, double dPixelX2, double dPixelY2)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCam, dRobotX1, dRobotY1, dRobotX2, dRobotY2, dPixelX1, dPixelY1, dPixelX2, dPixelY2);
	return result;
}

long CKOVISION::GetOffset2Point2Pos(long nCam, double dRobotX1, double dRobotY1, double dRobotX2, double dRobotY2, double dPixelX1, double dPixelY1, double dPixelX2, double dPixelY2, double* dOffsetX, double* dOffsetY, double* dAngle)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_PR8 VTS_PR8 VTS_PR8;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCam, dRobotX1, dRobotY1, dRobotX2, dRobotY2, dPixelX1, dPixelY1, dPixelX2, dPixelY2, dOffsetX, dOffsetY, dAngle);
	return result;
}

long CKOVISION::SetScaleFactor(long nCam, double dScaleFactor)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_R8;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCam, dScaleFactor);
	return result;
}

double CKOVISION::GetScaleFactor(long nCam)
{
	double result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		nCam);
	return result;
}

long CKOVISION::SaveAlignData(LPCTSTR pFileName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		pFileName);
	return result;
}

long CKOVISION::LoadAlignData(LPCTSTR pFileName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		pFileName);
	return result;
}

long CKOVISION::NewAlignData()
{
	long result;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CKOVISION::DeleteAlignData(LPCTSTR pFileName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		pFileName);
	return result;
}

long CKOVISION::MakeCalibrationXY(long nCam, double dMoveX, double dPixelX1, double dPixelY1, double dPixelX2, double dPixelY2, double dMoveY, double dPixelX3, double dPixelY3, double dPixelX4, double dPixelY4)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCam, dMoveX, dPixelX1, dPixelY1, dPixelX2, dPixelY2, dMoveY, dPixelX3, dPixelY3, dPixelX4, dPixelY4);
	return result;
}

long CKOVISION::GetOffset(long nCam, double dCx, double dCy, double dAngle, double* dOffsetX, double* dOffsetY, double* dOffAngle)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_R8 VTS_R8 VTS_R8 VTS_PR8 VTS_PR8 VTS_PR8;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCam, dCx, dCy, dAngle, dOffsetX, dOffsetY, dOffAngle);
	return result;
}

long CKOVISION::MakeCalibrationX(long nCam, double dMoveX, double dPixelX1, double dPixelY1, double dPixelX2, double dPixelY2)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCam, dMoveX, dPixelX1, dPixelY1, dPixelX2, dPixelY2);
	return result;
}

long CKOVISION::SetFilePath(LPCTSTR sFilePath)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		sFilePath);
	return result;
}

void CKOVISION::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
