#if !defined(AFX_KOVISION_H__D1F085BE_6928_40FA_BE55_30BCA17AB7D0__INCLUDED_)
#define AFX_KOVISION_H__D1F085BE_6928_40FA_BE55_30BCA17AB7D0__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CKOVISION wrapper class

class CKOVISION : public CWnd
{
protected:
	DECLARE_DYNCREATE(CKOVISION)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x4ebfc28b, 0xfcd, 0x11d5, { 0xb3, 0x83, 0x0, 0x50, 0xda, 0x28, 0xbb, 0xca } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long LineFittingHor(long dataN, double* x, double* y, long removeN, double ErrorLimit, double* t, double* a, double* b);
	long LineFittingVer(long dataN, double* x, double* y, long removeN, double ErrorLimit, double* t, double* a, double* b);
	long LineCrossPoint(double t1, double a1, double b1, double t2, double a2, double b2, double* cx, double* cy);
	long SetLineData(long nSlope, double dRemoveRate, double dLimitPixel);
	BOOL Open();
	long FindCornerPos(long fm, long left, long top, long right, long bottom, long nPitch, long nCorner_Pos, long nObject_Color, long nSkip, long Result_Show, long nAllowedRange, double* x, double* y, double* x_good_ratio, double* y_good_ratio);
	long FindVer2Line(long fm, long left, long top, long right, long bottom, long nPitch, double dObject_Width, long nObject_Color, long nSkip, long Result_Show, long nRotate_Range, double* t, double* a, double* b);
	long FindHor2Line(long fm, long left, long top, long right, long bottom, long nPitch, double dObject_Width, long nObject_Color, long nSkip, long Result_Show, long nRotate_Range, double* t, double* a, double* b);
	long FindImageAngle(long fm, long left, long top, long right, long bottom, long nPitch, double* pAngleTotal, double* pAngleMax);
	double FindWidth(long fm, long left, long top, long right, long bottom, long pitch, long nColor, long nDir, long nMinDiff, long nPixelOffset, long nFindMax, double* rx, double* ry);
	long FindWidth1(long fm, long left, long top, long right, long bottom, long pitch, long nColor, long nDir, long nMinDiff, long nPixelOffset, long nFindMax, double* rx, double* ry, double* widthNormal, double* widthShort);
	long ImageRotate(long fmS, long fmD, long left, long top, long right, long bottom, long pitch, double dCx, double dCy, double dAngle);
	long SetCodeData(long nCodeType, long nConfirm, long nSkipY, long nShowLine, long nShowAstrisk, long nDataSizeFixed, long nDataSize);
	long GetCodeData(long* nCodeType, long* nConfirm, long* nSkipY, long* nShowLine, long* nShowAstrisk, long* nDataSizeFixed, long* nDataSize);
	CString ReadBarcode(long fm, long left, long top, long right, long bottom, long pitch);
	long SaveCodeData(LPCTSTR pFileName);
	long LoadCodeData(LPCTSTR pFileName);
	CString ReadBarcode1(long fm, long left, long top, long right, long bottom, long pitch, long nProjNum, long nTry, long nStartDepth, long nEndDepth);
	CString ReadBarcodeVer(long fm, long left, long top, long right, long bottom, long pitch);
	CString ReadBarcode1Ver(long fm, long left, long top, long right, long bottom, long pitch, long ProjNum, long nTry, long nStartDepth, long nEndDepth);
	long SetBase(long nCam, double dCx, double dCy, double dAngle);
	long SetBase2Point(long nCam, double dCx1, double dCy1, double dCx2, double dCy2);
	long GetOffset2Point(long nCam, double dCx1, double dCy1, double dCx2, double dCy2, double* dOffsetX, double* dOffsetY, double* dAngle);
	long SetBase2Point2Pos(long nCam, double dRobotX1, double dRobotY1, double dRobotX2, double dRobotY2, double dPixelX1, double dPixelY1, double dPixelX2, double dPixelY2);
	long GetOffset2Point2Pos(long nCam, double dRobotX1, double dRobotY1, double dRobotX2, double dRobotY2, double dPixelX1, double dPixelY1, double dPixelX2, double dPixelY2, double* dOffsetX, double* dOffsetY, double* dAngle);
	long SetScaleFactor(long nCam, double dScaleFactor);
	double GetScaleFactor(long nCam);
	long SaveAlignData(LPCTSTR pFileName);
	long LoadAlignData(LPCTSTR pFileName);
	long NewAlignData();
	long DeleteAlignData(LPCTSTR pFileName);
	long MakeCalibrationXY(long nCam, double dMoveX, double dPixelX1, double dPixelY1, double dPixelX2, double dPixelY2, double dMoveY, double dPixelX3, double dPixelY3, double dPixelX4, double dPixelY4);
	long GetOffset(long nCam, double dCx, double dCy, double dAngle, double* dOffsetX, double* dOffsetY, double* dOffAngle);
	long MakeCalibrationX(long nCam, double dMoveX, double dPixelX1, double dPixelY1, double dPixelX2, double dPixelY2);
	long SetFilePath(LPCTSTR sFilePath);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_KOVISION_H__D1F085BE_6928_40FA_BE55_30BCA17AB7D0__INCLUDED_)
