// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ligeledisplay.h"

/////////////////////////////////////////////////////////////////////////////
// CLigEleDisplay

IMPLEMENT_DYNCREATE(CLigEleDisplay, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CLigEleDisplay properties

/////////////////////////////////////////////////////////////////////////////
// CLigEleDisplay operations

long CLigEleDisplay::Open(long idSystem, long idFrame, long idOverlay)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		idSystem, idFrame, idOverlay);
	return result;
}

void CLigEleDisplay::Close()
{
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CLigEleDisplay::DrawCrossLine(long cX, long cY, long wSize, unsigned long color)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 cX, cY, wSize, color);
}

void CLigEleDisplay::DrawLine(long sX, long sY, long eX, long eY, unsigned long color)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 sX, sY, eX, eY, color);
}

void CLigEleDisplay::DrawRect(long left, long top, long right, long bottom, unsigned long color)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 left, top, right, bottom, color);
}

void CLigEleDisplay::ClearOvr()
{
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CLigEleDisplay::TextOut(LPCTSTR str, long sX, long sY, unsigned long color)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 str, sX, sY, color);
}

void CLigEleDisplay::RestoreOverlay()
{
	InvokeHelper(0x8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CLigEleDisplay::ImagePan(long nDx, long nDY)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nDx, nDY);
	return result;
}

long CLigEleDisplay::ImageZoom(long nX, long nY)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nX, nY);
	return result;
}

long CLigEleDisplay::SetWindowSize(long nWidth, long nHeight)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nWidth, nHeight);
	return result;
}

long CLigEleDisplay::ShowOverlay(BOOL nShow)
{
	long result;
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nShow);
	return result;
}

long CLigEleDisplay::GetDisplayID()
{
	long result;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

void CLigEleDisplay::UpdateDisplay()
{
	InvokeHelper(0xe, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CLigEleDisplay::AddROI(LPCTSTR sROIname, long left, long top, long right, long bottom, long color)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		sROIname, left, top, right, bottom, color);
	return result;
}

long CLigEleDisplay::DeleteROI(LPCTSTR sROIname)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		sROIname);
	return result;
}

long CLigEleDisplay::DeleteAllROI()
{
	long result;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CLigEleDisplay::GetRegionROI(LPCTSTR sROIname, long* left, long* top, long* right, long* bottom)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI4;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		sROIname, left, top, right, bottom);
	return result;
}

long CLigEleDisplay::ModifyROI(LPCTSTR sROIname, long moveX, long moveY, long sizeX, long sizeY)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		sROIname, moveX, moveY, sizeX, sizeY);
	return result;
}

BOOL CLigEleDisplay::ROIMouseControl(BOOL flag)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		flag);
	return result;
}

void CLigEleDisplay::SetImageSize(long width, long height)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 width, height);
}

void CLigEleDisplay::TextOutFont(LPCTSTR str, long sX, long sY, long size, LPCTSTR font, unsigned long color)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_I4 VTS_BSTR VTS_I4;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 str, sX, sY, size, font, color);
}

void CLigEleDisplay::DrawCircle(long cX, long cY, long radius, unsigned long color)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 cX, cY, radius, color);
}
