#if !defined(AFX_LIGELEDISPLAY_H__702E5C70_5E03_48EC_B86E_8909AD262F2C__INCLUDED_)
#define AFX_LIGELEDISPLAY_H__702E5C70_5E03_48EC_B86E_8909AD262F2C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLigEleDisplay wrapper class

class CLigEleDisplay : public CWnd
{
protected:
	DECLARE_DYNCREATE(CLigEleDisplay)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x147cf04f, 0xd4d8, 0x11d4, { 0xbd, 0xe1, 0x0, 0x60, 0x8, 0x33, 0x9e, 0xe8 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long Open(long idSystem, long idFrame, long idOverlay);
	void Close();
	void DrawCrossLine(long cX, long cY, long wSize, unsigned long color);
	void DrawLine(long sX, long sY, long eX, long eY, unsigned long color);
	void DrawRect(long left, long top, long right, long bottom, unsigned long color);
	void ClearOvr();
	void TextOut(LPCTSTR str, long sX, long sY, unsigned long color);
	void RestoreOverlay();
	long ImagePan(long nDx, long nDY);
	long ImageZoom(long nX, long nY);
	long SetWindowSize(long nWidth, long nHeight);
	long ShowOverlay(BOOL nShow);
	long GetDisplayID();
	void UpdateDisplay();
	long AddROI(LPCTSTR sROIname, long left, long top, long right, long bottom, long color);
	long DeleteROI(LPCTSTR sROIname);
	long DeleteAllROI();
	long GetRegionROI(LPCTSTR sROIname, long* left, long* top, long* right, long* bottom);
	long ModifyROI(LPCTSTR sROIname, long moveX, long moveY, long sizeX, long sizeY);
	BOOL ROIMouseControl(BOOL flag);
	void SetImageSize(long width, long height);
	void TextOutFont(LPCTSTR str, long sX, long sY, long size, LPCTSTR font, unsigned long color);
	void DrawCircle(long cX, long cY, long radius, unsigned long color);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LIGELEDISPLAY_H__702E5C70_5E03_48EC_B86E_8909AD262F2C__INCLUDED_)
