#if !defined(AFX_MILGRABBER_H__0B77DD23_BCC3_4F0F_9847_C29AF30F1989__INCLUDED_)
#define AFX_MILGRABBER_H__0B77DD23_BCC3_4F0F_9847_C29AF30F1989__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMilGrabber wrapper class

class CMilGrabber : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMilGrabber)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd3a508db, 0x235, 0x4838, { 0x96, 0x20, 0xa2, 0xd4, 0x6d, 0x9a, 0x11, 0x5d } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetSystemID();
	long GetImageID(long nCamera);
	long GetDisplayID(long nDIsplay);
	long GetImagePtr(long nCamera);
	long LoadBMP(long nCamera, LPCTSTR FileName);
	long SaveBMP(long nCamera, LPCTSTR FileName);
	long PutImage(long nCamera, long fmSource);
	long Open();
	long Close();
	long CopyFrame(long srcFrame, long dstFrame);
	long SetDisplay(long nCam, long pDisplay);
	long SetDelayTime(long nMiliSecond);
	void Grab(long nCam);
	void Live(long nCam);
	BOOL IsLive(long nCam);
	long GetDisplay(long nCam);
	long Open1();
	long OpenDCF(long nBoardID, BOOL bMuitiGrab, LPCTSTR sFilename);
	void SetChannel(long nChannel);
	long GetChannel();
	void ImageReverse(BOOL bXReverse, BOOL nYReverse);
	void FastGrab(long nCam);
	void UpdateDisplay(long nCam);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MILGRABBER_H__0B77DD23_BCC3_4F0F_9847_C29AF30F1989__INCLUDED_)
