// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "milgrabber.h"

/////////////////////////////////////////////////////////////////////////////
// CMilGrabber

IMPLEMENT_DYNCREATE(CMilGrabber, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMilGrabber properties

/////////////////////////////////////////////////////////////////////////////
// CMilGrabber operations

long CMilGrabber::GetSystemID()
{
	long result;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CMilGrabber::GetImageID(long nCamera)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCamera);
	return result;
}

long CMilGrabber::GetDisplayID(long nDIsplay)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nDIsplay);
	return result;
}

long CMilGrabber::GetImagePtr(long nCamera)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCamera);
	return result;
}

long CMilGrabber::LoadBMP(long nCamera, LPCTSTR FileName)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCamera, FileName);
	return result;
}

long CMilGrabber::SaveBMP(long nCamera, LPCTSTR FileName)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCamera, FileName);
	return result;
}

long CMilGrabber::PutImage(long nCamera, long fmSource)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCamera, fmSource);
	return result;
}

long CMilGrabber::Open()
{
	long result;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CMilGrabber::Close()
{
	long result;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CMilGrabber::CopyFrame(long srcFrame, long dstFrame)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		srcFrame, dstFrame);
	return result;
}

long CMilGrabber::SetDisplay(long nCam, long pDisplay)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCam, pDisplay);
	return result;
}

long CMilGrabber::SetDelayTime(long nMiliSecond)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nMiliSecond);
	return result;
}

void CMilGrabber::Grab(long nCam)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_EMPTY, NULL, parms,nCam);
}

void CMilGrabber::Live(long nCam)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nCam);
}

BOOL CMilGrabber::IsLive(long nCam)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nCam);
	return result;
}

long CMilGrabber::GetDisplay(long nCam)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCam);
	return result;
}

long CMilGrabber::Open1()
{
	long result;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CMilGrabber::OpenDCF(long nBoardID, BOOL bMuitiGrab, LPCTSTR sFilename)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BOOL VTS_BSTR;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nBoardID, bMuitiGrab, sFilename);
	return result;
}

void CMilGrabber::SetChannel(long nChannel)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nChannel);
}

long CMilGrabber::GetChannel()
{
	long result;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

void CMilGrabber::ImageReverse(BOOL bXReverse, BOOL nYReverse)
{
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bXReverse, nYReverse);
}

void CMilGrabber::FastGrab(long nCam)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nCam);
}

void CMilGrabber::UpdateDisplay(long nCam)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nCam);
}

void CMilGrabber::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
