// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "pmocx.h"

/////////////////////////////////////////////////////////////////////////////
// CPMOCX

IMPLEMENT_DYNCREATE(CPMOCX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CPMOCX properties

/////////////////////////////////////////////////////////////////////////////
// CPMOCX operations

long CPMOCX::PMSetSearchFrame(long searchfm)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		searchfm);
	return result;
}

long CPMOCX::PMClose()
{
	long result;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CPMOCX::PMLoad(LPCTSTR pFileName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		pFileName);
	return result;
}

long CPMOCX::PMSave(LPCTSTR pFileName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		pFileName);
	return result;
}

long CPMOCX::PMSetRedraw(BOOL flag)
{
	long result;
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		flag);
	return result;
}

long CPMOCX::PMCopyPattern(long nDstId, long nSrcId)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nDstId, nSrcId);
	return result;
}

long CPMOCX::PMClearWindow()
{
	long result;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CPMOCX::PMShowPatternNum(BOOL flag)
{
	long result;
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		flag);
	return result;
}

long CPMOCX::PMRegister(long fm, long left, long top, long right, long bottom, long pitch)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		fm, left, top, right, bottom, pitch);
	return result;
}

long CPMOCX::PMSetReturnPoint(double dRx, double dRy)
{
	long result;
	static BYTE parms[] =
		VTS_R8 VTS_R8;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		dRx, dRy);
	return result;
}

long CPMOCX::PMChangeROIColor(long nR, long nG, long nB)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nR, nG, nB);
	return result;
}

long CPMOCX::PMChangeHwnd(long hwnd, long left, long top, long right, long bottom)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		hwnd, left, top, right, bottom);
	return result;
}

long CPMOCX::PMAddPattern(long nAddNum)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nAddNum);
	return result;
}

long CPMOCX::PMSetPatternId(long nId)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nId);
	return result;
}

long CPMOCX::PMGetPatternNum()
{
	long result;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CPMOCX::PMSearch()
{
	long result;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CPMOCX::PMSearchId(long nId)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nId);
	return result;
}

long CPMOCX::PMGetReturn(long N, double* dRx, double* dRy, long* nScore, double* dAngle)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_PR8 VTS_PR8 VTS_PI4 VTS_PR8;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		N, dRx, dRy, nScore, dAngle);
	return result;
}

long CPMOCX::PMSetSearchArea(long left, long top, long right, long bottom, long pitch)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		left, top, right, bottom, pitch);
	return result;
}

long CPMOCX::PMSetPatternName(LPCTSTR pPatternName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		pPatternName);
	return result;
}

long CPMOCX::PMSetDrawCross(BOOL flag)
{
	long result;
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		flag);
	return result;
}

long CPMOCX::PMSetDrawRectangle(BOOL flag)
{
	long result;
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		flag);
	return result;
}

long CPMOCX::PMSetDisplayID(long nDispID)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nDispID);
	return result;
}

long CPMOCX::MARKResgister(long nColor, long nUseEdge, long nWidthRange, long nHeightRange, long nAreaRange, double* rx, double* ry)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_PR8 VTS_PR8;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nColor, nUseEdge, nWidthRange, nHeightRange, nAreaRange, rx, ry);
	return result;
}

long CPMOCX::MARKSearch(long* nScore, double* rx, double* ry)
{
	long result;
	static BYTE parms[] =
		VTS_PI4 VTS_PR8 VTS_PR8;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nScore, rx, ry);
	return result;
}

long CPMOCX::PMCreate(long nMaxPatternNum)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nMaxPatternNum);
	return result;
}

long CPMOCX::PMDialog(long nPatternId, long hwndDisplay, long nWidth, long nHeight, long nPanX, long nPanY, double dZoom)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_R8;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nPatternId, hwndDisplay, nWidth, nHeight, nPanX, nPanY, dZoom);
	return result;
}

long CPMOCX::PMBMPRegister(LPCTSTR sFileName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		sFileName);
	return result;
}

long CPMOCX::PMSaveBMP(LPCTSTR sFileName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		sFileName);
	return result;
}

long CPMOCX::PMGetPatternData(long* fm, long* width, long* height, long* pitch, double* rx, double* ry)
{
	long result;
	static BYTE parms[] =
		VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI4 VTS_PR8 VTS_PR8;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		fm, width, height, pitch, rx, ry);
	return result;
}

long CPMOCX::PMGetSearchArea(long* left, long* top, long* right, long* bottom, long* pitch)
{
	long result;
	static BYTE parms[] =
		VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI4;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		left, top, right, bottom, pitch);
	return result;
}

long CPMOCX::PMGetThreshold()
{
	long result;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CPMOCX::PMSearchOne(long nId, long fm, long left, long top, long right, long bottom, long pitch, double* dX, double* dY, long* nScore, double* dAngle)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_PR8 VTS_PR8 VTS_PI4 VTS_PR8;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nId, fm, left, top, right, bottom, pitch, dX, dY, nScore, dAngle);
	return result;
}

long CPMOCX::PMNew()
{
	long result;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CPMOCX::PMDelete(LPCTSTR pFileName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		pFileName);
	return result;
}

long CPMOCX::SetFilePath(LPCTSTR sFileName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x24, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		sFileName);
	return result;
}

void CPMOCX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CPMOCX::BLOBSetAreaLimit(BOOL bABS, BOOL bFROM, long nFromPixel, BOOL bTO, long nToPixel)
{
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL VTS_I4 VTS_BOOL VTS_I4;
	InvokeHelper(0x31, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bABS, bFROM, nFromPixel, bTO, nToPixel);
}

void CPMOCX::BLOBSetAutoThreshold(BOOL flag)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x30, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 flag);
}

long CPMOCX::BLOBProcessArea(long left, long top, long right, long bottom)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x2f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		left, top, right, bottom);
	return result;
}

long CPMOCX::BLOBGetRectangle(long N, long* left, long* top, long* right, long* bottom)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI4;
	InvokeHelper(0x2e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		N, left, top, right, bottom);
	return result;
}

double CPMOCX::BLOBGetAngle(long N)
{
	double result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x2d, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		N);
	return result;
}

double CPMOCX::BLOBGetCompactness(long N)
{
	double result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x2c, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		N);
	return result;
}

long CPMOCX::BLOBGetPerimeter(long N)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x2b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		N);
	return result;
}

long CPMOCX::BLOBGetCenter(long N, double* dCx, double* dCy)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_PR8 VTS_PR8;
	InvokeHelper(0x2a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		N, dCx, dCy);
	return result;
}

double CPMOCX::BLOBGetArea(long N)
{
	double result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x29, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		N);
	return result;
}

long CPMOCX::BLOBProcess()
{
	long result;
	InvokeHelper(0x28, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

void CPMOCX::BLOBSetTouchAllow(BOOL bLeft, BOOL bTop, BOOL bRight, BOOL bBottom)
{
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL;
	InvokeHelper(0x27, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bLeft, bTop, bRight, bBottom);
}

void CPMOCX::BLOBSetThreshold(long nThreshold)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x26, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nThreshold);
}

void CPMOCX::BLOBSetObjectColor(long nObjectColor)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nObjectColor);
}