#if !defined(AFX_PMOCX_H__B283084D_5603_4C3C_8C19_765A5FBF442F__INCLUDED_)
#define AFX_PMOCX_H__B283084D_5603_4C3C_8C19_765A5FBF442F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPMOCX wrapper class

class CPMOCX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CPMOCX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xcea12ae0, 0xf0a0, 0x11d5, { 0xb3, 0x83, 0x0, 0x50, 0xda, 0x28, 0xbb, 0xca } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long PMSetSearchFrame(long searchfm);
	long PMClose();
	long PMLoad(LPCTSTR pFileName);
	long PMSave(LPCTSTR pFileName);
	long PMSetRedraw(BOOL flag);
	long PMCopyPattern(long nDstId, long nSrcId);
	long PMClearWindow();
	long PMShowPatternNum(BOOL flag);
	long PMRegister(long fm, long left, long top, long right, long bottom, long pitch);
	long PMSetReturnPoint(double dRx, double dRy);
	long PMChangeROIColor(long nR, long nG, long nB);
	long PMChangeHwnd(long hwnd, long left, long top, long right, long bottom);
	long PMAddPattern(long nAddNum);
	long PMSetPatternId(long nId);
	long PMGetPatternNum();
	long PMSearch();
	long PMSearchId(long nId);
	long PMGetReturn(long N, double* dRx, double* dRy, long* nScore, double* dAngle);
	long PMSetSearchArea(long left, long top, long right, long bottom, long pitch);
	long PMSetPatternName(LPCTSTR pPatternName);
	long PMSetDrawCross(BOOL flag);
	long PMSetDrawRectangle(BOOL flag);
	long PMSetDisplayID(long nDispID);
	long MARKResgister(long nColor, long nUseEdge, long nWidthRange, long nHeightRange, long nAreaRange, double* rx, double* ry);
	long MARKSearch(long* nScore, double* rx, double* ry);
	long PMCreate(long nMaxPatternNum);
	long PMDialog(long nPatternId, long hwndDisplay, long nWidth, long nHeight, long nPanX, long nPanY, double dZoom);
	long PMBMPRegister(LPCTSTR sFileName);
	long PMSaveBMP(LPCTSTR sFileName);
	long PMGetPatternData(long* fm, long* width, long* height, long* pitch, double* rx, double* ry);
	long PMGetSearchArea(long* left, long* top, long* right, long* bottom, long* pitch);
	long PMGetThreshold();
	long PMSearchOne(long nId, long fm, long left, long top, long right, long bottom, long pitch, double* dX, double* dY, long* nScore, double* dAngle);
	long PMNew();
	long PMDelete(LPCTSTR pFileName);
	long SetFilePath(LPCTSTR sFileName);
	void BLOBSetObjectColor(long nObjectColor);
	void BLOBSetThreshold(long nThreshold);
	void BLOBSetTouchAllow(BOOL bLeft, BOOL bTop, BOOL bRight, BOOL bBottom);
	long BLOBProcess();
	double BLOBGetArea(long N);
	long BLOBGetCenter(long N, double* dCx, double* dCy);
	long BLOBGetPerimeter(long N);
	double BLOBGetCompactness(long N);
	double BLOBGetAngle(long N);
	long BLOBGetRectangle(long N, long* left, long* top, long* right, long* bottom);
	long BLOBProcessArea(long left, long top, long right, long bottom);
	void BLOBSetAutoThreshold(BOOL flag);
	void BLOBSetAreaLimit(BOOL bABS, BOOL bFROM, long nFromPixel, BOOL bTO, long nToPixel);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PMOCX_H__B283084D_5603_4C3C_8C19_765A5FBF442F__INCLUDED_)
